name: learn-github-actions
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 # 检查环境
      - uses: actions/setup-node@v2 # 搭建node环境
        with:
          node-version: '14'
      - run: npm install -g bats
      - run: bats -v